language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - "pip install poetry"
  - "poetry develop"
script:
  - "pytest ./tests/"
addons:
  artifacts:
    paths:
      - '$(ls -1 dist/*.zip | tr "\n" ":")'
  s3_region: "us-east-1"
notifications:
  email: false
